# Site settings
title: xhpw - an Openshift cartridge for supercharged Wordpress sites
tag_text: xhpw
description: xhpw is a ready to deploy Openshift cartridge.

# Build settings
markdown: kramdown

exclude: ["README.md"]
